### ISSUE TITLE
Replays sometimes are created with filesize of 0

### ISSUE THREAD

**Issue by dguenther** [The-Velvet-Room/deja-vu#13]
Replays can, under some circumstances, get written as an empty file. I don't have repro steps myself since I just heard about it, but I'd like to start an issue for it. 

@Camtendo do you have any more details you could fill in?

**Comment by Camtendo** [comment]
On Brian's Laptop:
1. Start OBS's replay buffer
2. Start watching the directory where the buffer is written with Deja Vu
3. Save the replay buffer
4. After Derek's "Vegas Build" Deja Vu moves files successfully, but the replays have size zero so mkv stretching fails

Upon stopping watching the directory, OBS is able to write the proper replay buffers. I think we aren't letting the replay write finish somehow, similar to an issue Derek fixed earlier. I think the issue is also somehow related to CPU speed this time though.

**Comment by dguenther** [comment]
So before the Vegas build, OBS wouldn't write any files at all, but after it, OBS would write empty files?

**Comment by Camtendo** [comment]
I believe so. The crashes definitely stopped for good after the Vegas build..
